apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  ports:
  - protocol: TCP
    port: 8001
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: movie-service
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  selector:
    app: movie-db
  ports:
    - protocol: TCP
      port: 5432
  type: ClusterIP
